version: '3.8'

services:
  warolabs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warolabs-nuxt
    ports:
      - "3000:3000"
    volumes:
      - nuxt-data:/app/storage
    networks:
      - warolabs-network
    restart: unless-stopped

networks:
  warolabs-network:
    external: true

volumes:
  nuxt-data: