services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warolabs-nuxt
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://saifer:96&Gd'2H+zjR@saifer-postgres-1:5432/postresWaroLabs
      - REDIS_URL=redis://:3M[oG8QlNw)n!5@*n@rediswarolabs-redis-1:6379
    volumes:
      - nuxt-data:/app/storage
    networks:
      - warolabs-network
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: saifer-postgres-1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=saifer
      - POSTGRES_PASSWORD=96&Gd'2H+zjR
      - POSTGRES_DB=postresWaroLabs
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - warolabs-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: rediswarolabs-redis-1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - warolabs-network
    restart: unless-stopped

networks:
  warolabs-network:
    external: true

volumes:
  nuxt-data:
  postgres-data:
    name: d4903c977cd4a36d0e4401f938008af6b9a5246681a34fc5883dcfa51f8fd631
  redis-data:
    name: 2c14ef428eccc2677ec3b17283c6026514ed7af61c1741392730fa97e10640b9